export const signInStyles = {
      container: {
        backgroundColor: 'lightgrey',
        minHeight: '100vh',
        color: 'black',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
      },
      formContainer: {
        width: '450px',
        backgroundColor: 'white',
        borderRadius: '10px',
        boxShadow: '0 4px 8px rgba(0,0,0,0.1)',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        padding: '20px',
        margin: 'auto',
      },
      title: {
        textAlign: 'left',
        marginTop: '20px',
        marginBottom: '20px',
        width: '100%',
        marginLeft: '20px',
      },
      form: {
        width: '400px',
        backgroundColor: 'white',
        borderRadius: '10px',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        padding: '20px',
        margin: 'auto',
      },
      button: {
        backgroundColor: '#5ceb28',
        color: 'white',
        width: '350px',
        marginBottom: '10px',
      },
      hrContainer: {
        width: '100%',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        margin: '10px 0',
      },
      hr: {
        width: '35%',
        borderBottom: '1px solid black',
        margin: '0 10px',
      },
      signUpButton: {
        backgroundColor: '#555',
        color: 'white',
        width: '350px',
        marginBottom: '20px',
      },
      formFieldError: {
        borderColor: 'red',
      },
      formFieldErrorMessage: {
        color: 'red',
        fontSize: '0.875em',
        height: '1em',
      },
      };